name: yoga_mithra
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Versioning
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0' # Use the stable SDK version

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0
  camera_android_camerax: 0.6.7+2
  flutter_plugin_android_lifecycle: ^2.0.2
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_tts: ^3.8.5
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.20.2
  path_provider: ^2.1.1
  curved_navigation_bar: ^1.0.6
  image_picker: ^1.1.2
  http: ^1.3.0
  permission_handler: ^11.3.1
  get: ^4.6.6
  loading_indicator: ^3.1.1
  fluttertoast: ^8.2.6
  audioplayers: ^5.2.0
  image: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - lib/assets/login.png # Login screen image
    - assets/images/   # Additional images

  # Fonts (if needed)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700